### ISSUE TITLE
Please help review this project

### ISSUE THREAD

**Issue by mattcui** [mattcui/stemcell-post-install#1]
@maximilien I would like you to help review this project. I already completed coding work and passed some basic testing. I just used fake packages for IEM agent and IBM security script packages. For the PID issue of IEM agent, I simply grep the process id with ps command and save it in a pid file, which means the code helps generate a pid file for IEM agent process. For IBM security package, there generated a .done file to mark the package is applied. The working branch is master. Please let me know if you have any comment/concern. Thanks.

**Comment by maximilien** [comment]
Looks great to me. I assume you've already tested it on a CF deploy using eCPI and latest stemcell?
